# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='packId',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
