# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentId', models.CharField(max_length=20)),
            ],
        ),
    ]
